CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL, cash NUMERIC NOT NULL DEFAULT 10000.00, 'init_cash' NUMERIC NOT NULL DEFAULT 10000);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE transactions (transaction_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, symbol TEXT NOT NULL, unit_price NUMERIC NOT NULL DEFAULT 0, shares INTEGER NOT NULL, price NUMERIC NOT NULL DEFAULT 0, purchase_time TIMESTAMP NOT NULL, type TEXT);
CREATE TABLE ownership (stock_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, symbol TEXT NOT NULL, shares INTEGER NOT NULL);
CREATE UNIQUE INDEX username ON users (username);
CREATE UNIQUE INDEX transaction_id ON transactions (transaction_id);
